### ISSUE TITLE
definition for pose

### ISSUE THREAD

**Issue by twojtasz** [uber/xviz#26]
Currently the **pose** often named **vehicle_pose** is not well defined but MUST contains some fields in order to operate with streetscape.

Proposal is to define **pose** as the following:
```
{
  x: number,
  y: number,
  z: number,
  longitude: number,
  latitude: number,
  altitude: number,
  pitch: number,
  roll: number,
  yaw: number,
  time: number
}
```
**longitude, latitude, altitude** are geospatial coordinates that anchor this pose
**x, y, z** are meter offsets from the specified geospatial coordinates
**roll, yaw, pitch** are the orientation of the object
**time** is the GPS timestamp this pose was captured and serves as the main time signal for synchronization across all streams for visualization.

Alternative definition:
```
{
  time: number,
  mapOrigin: {
    longitude: number,
    latitude: number,
    altitude: number
  },
  position: {
    x: number,
    y: number,
    z: number
  },
  orientation: {
    pitch: number,
    roll: number,
    yaw: number
  }
}
```

**Comment by KevinYuk** [comment]
> Currently the **pose** often named **vehicle_pose** is not well defined but MUST contains some fields in order to operate with streetscape.
> 
> Proposal is to define **pose** as the following:
> 
> ```
> {
>   x: number,
>   y: number,
>   z: number,
>   longitude: number,
>   latitude: number,
>   altitude: number,
>   pitch: number,
>   roll: number,
>   yaw: number,
>   time: number
> }
> ```
> 
> **longitude, latitude, altitude** are geospatial coordinates that anchor this pose
> **x, y, z** are meter offsets from the specified geospatial coordinates
> **roll, yaw, pitch** are the orientation of the object
> **time** is the GPS timestamp this pose was captured and serves as the main time signal for synchronization across all streams for visualization.
> 
> Alternative definition:
> 
> ```
> {
>   time: number,
>   mapOrigin: {
>     longitude: number,
>     latitude: number,
>     altitude: number
>   },
>   position: {
>     x: number,
>     y: number,
>     z: number
>   },
>   orientation: {
>     pitch: number,
>     roll: number,
>     yaw: number
>   }
> }
> ```

Hi @twojtasz ,

I find that in the kitti example, you guys fill the field like below which is different as you said here. Could you please explain it? Thanks a lot.

`    resMap.pose = {
      timestamp,
      latitude: Number(lat),
      longitude: Number(lon),
      altitude: Number(alt),
      roll: Number(roll),
      pitch: Number(pitch),
      yaw: Number(yaw)
    };

    resMap.velocity = {
      timestamp,
      'velocity-north': Number(vn),
      'velocity-east': Number(ve),
      'velocity-forward': Number(vf),
      'velocity-left': Number(vl),
      'velocity-upward': Number(vu),
      'angular-rate-x': Number(wx),
      'angular-rate-y': Number(wy),
      'angular-rate-z': Number(wz),
      'angular-rate-forward': Number(wf),
      'angular-rate-left': Number(wl),
      'angular-rate-upward': Number(wu)
    };

    resMap.acceleration = {
      timestamp,
      'acceleration-x': Number(ax),
      'acceleration-y': Number(ay),
      'acceleration-z': Number(az),
      'acceleration-forward': Number(af),
      'acceleration-left': Number(al),
      'acceleration-upward': Number(au)
    };`
