### ISSUE TITLE
Python XVIZ Builder

### ISSUE THREAD

**Issue by twojtasz** [uber/xviz#33]

**Comment by gerardsimons** [comment]
Do you anticipate it to have all of the features that the JavaScript version has?

**Comment by cmpute** [comment]
Is there any preliminary code sample that you have been working on? I'm looking for a python data server for xviz. If not, I also want to contribute to build a python based data provider using websocket

**Comment by twojtasz** [comment]
@cmpute contributed our initial python libraries.
