### ISSUE TITLE
API doc for XVIZStyleParser refers to xviz-stream-buffer.md

### ISSUE THREAD

**Issue by tiffon** [uber/xviz#359]
`pages.json` reference is incorrect:

https://github.com/uber/xviz/blob/7419314fcc506c525b6aa31800b81d4553e468d6/website/pages.json#L258-L261

**Comment by twojtasz** [comment]
Fixed in https://github.com/uber/xviz/commit/d3b2c10d8b2cdc9d60a585d2a2e9c878c2fc4a75.

Thank you!
