### ISSUE TITLE
ros data to xviz

### ISSUE THREAD

**Issue by pgh41** [uber/xviz#380]
Is it possible converting ros x.bag data to xviz?
if it is possible how can i do it?

**Comment by jlisee** [comment]
Now that @twojtasz has his account back I am closing this as a duplicate of #372.  That covers an offline conversion tool/library.

**Comment by draware** [comment]
@twojtasz possible to share any update? It would be great for our project. If you are busy it would be great to get some pointers to your approach and I'm happy complete and contribute it back.

**Comment by jlisee** [comment]
@twojtasz is making progress building out the server code infrastructure:

 - #435 - the IO module
 - #453 - the server module

Next up is a formal version of his ROS code.
