### ISSUE TITLE
Ensure spec uses snake_case and not camelCase

### ISSUE THREAD

**Issue by twojtasz** [uber/xviz#394]
Our spec has the convention of using *snake_case* and out API has used *camelCase*.  Fix the places in the spec where we have mistakenly used *camelCase*.

Locations:
 - mapOrigin in **Pose**
 - displayObjectId in **declarative UI**
 - independentVariable in **declarative UI**
 - dependentVariable in **declarative UI**

**Comment by twojtasz** [comment]
@jlisee should we just address **map_origin** and leave decl ui alone?

**Comment by tgorkin** [comment]
We are ignoring the declarative UI camel casing for now.
