### ISSUE TITLE
Can't download PDF Invoice

### ISSUE THREAD

**Issue by dpetzer** [uber/xviz#431]
Login to rider.uber.com
Asks me to give my location, choose skip down the bottom
Go to My Trips
Click on a trip
Click on Save Invoice
Text changes to Loading and spins forever
![image](https://user-images.githubusercontent.com/8804266/56777662-1147d400-6816-11e9-968c-215697a8e3f7.png)

Tried this in Firefox, Chrome, IE10.

Receipt is no good, need invoice.

**Comment by dpetzer** [comment]
Login to rider.uber.com
Asks me to give my location, choose skip down the bottom
Go to My Trips
Click on a trip
Click on Save Invoice 
Text changes to Loading and spins forever
![image](https://user-images.githubusercontent.com/8804266/56777566-9979a980-6815-11e9-99e7-edf0df16e02d.png)

Tried this in Firefox, Chrome, IE10.

Receipt is no good, need invoice.

**Comment by twojtasz** [comment]
@dpetzer Sorry, this has nothing to do with https://rider.uber.com

I suggest following the instructions in the link to file a support request. https://help.uber.com/riders/article/how-to-contact-support?nodeId=4c69afef-5739-4842-9e98-ed0087b873db

**Comment by dpetzer** [comment]
@twojtasz you are a champion.
