### ISSUE TITLE
version v1.0.0-beta.9 results in error in lidar points generation

### ISSUE THREAD

**Issue by pkulijing** [uber/xviz#450]
I was using version v1.0.0-beta.8 and my lidar data could be generated correctly as a `point` primitive, similar to what is done in the kitti converter example. But after upgrading to v1.0.0-beta.9, without any change to my own code, the lidar points are absent, and the related part in the generated glb file is null:
![image](https://user-images.githubusercontent.com/8855474/57698876-3dbe7580-7689-11e9-9134-74b13508b143.png)
In v1.0.0-beta.8 that same part was something like this:
![image](https://user-images.githubusercontent.com/8855474/57699502-6f840c00-768a-11e9-833d-8a3120e9acf4.png)

I noticed that version v1.0.0-beta.9 included [a commit related to flatten arrays](https://github.com/uber/xviz/commit/10f504bef1d6be8deaa8303f02343e1b861fcc34), in which the [parse-lidar-points.js](https://github.com/uber/xviz/commit/10f504bef1d6be8deaa8303f02343e1b861fcc34#diff-ecf77a509d898ec971a5b569485034a1) file in the kitti converter example was modified. Is this a bug or a backward-incompatible change? If the latter is the case, then I think the [documentation ](https://avs.auto/#/xviz/getting-started/converting-to-xviz/mapping-data-to-xviz/lidar?section=lidar-scans)needs to be updated.

**Comment by twojtasz** [comment]
@pkulijing I believe this is a bug that is fixed in https://github.com/uber/xviz/commit/8252902afbaf14a13b706a379f1660f084217d6b

I am waiting for another change to land then I can release a new beta.

**Comment by twojtasz** [comment]
I just published **v1.0.0-beta.13**. Please update and try again. Thanks!

**Comment by twojtasz** [comment]
@pkulijing I believe this is fixed and was a problem with just the beta.9 release

**Comment by pkulijing** [comment]
I can confirm that the problem no longer exists in beta.16.
