### ISSUE TITLE
can xviz server connect kafka as datasource

### ISSUE THREAD

**Issue by Questionboy** [uber/xviz#460]
hi,
I collect data from kafka. so, can xviz connect kafka and transform the data to xviz protocol?

**Comment by twojtasz** [comment]
@Questionboy that is not something we provide out of the box.  We will be releasing an XVIZ server module which you should be able to use to implement a connection to a kafka stream and convert to XVIZ and send down the websocket to the client.

**Comment by Questionboy** [comment]
thank you, look forward to it.

**Comment by qinchaofeng** [comment]
looking forward  too
