### ISSUE TITLE
Is there a repetition of timestamp, is there any understanding error?

### ISSUE THREAD

**Issue by truewhite** [uber/xviz#479]
Both the streamset and the pose contain timestamp information. Is this repeated?
![Screenshot from 2019-06-11 10-50-27](https://user-images.githubusercontent.com/50393648/59240421-fa7b0680-8c36-11e9-8234-b5cdc7aae6f5.png)
![Screenshot from 2019-06-11 10-47-43](https://user-images.githubusercontent.com/50393648/59240424-fcdd6080-8c36-11e9-8ac1-282d68bdf333.png)
![Screenshot from 2019-06-11 10-47-06](https://user-images.githubusercontent.com/50393648/59240429-023aab00-8c37-11e9-95e4-b4479d85041f.png)

**Comment by twojtasz** [comment]
Yes.  The short history is we used to rely on the `/vehicle_pose` timestamp, but
1. there could be multiple poses eventually
2. there could be _no_ poses eventually
3. we wanted the timestamp to be at the streamset level

Furthermore, the streamset represents whatever you want to display at that time.  However it could have data that comes from different times, so there are other places where timestamp comes into play as well.

For example, if you have data across a system that operates at different rates, you could display an instance @ T1000, but that could have data that comes from T999.7.
