### ISSUE TITLE
How can I convert my dataset into xviz protocol?

### ISSUE THREAD

**Issue by LinLidi** [uber/xviz#486]
Hi,
I have just start a streetscape.gl example with xviz stream data which is kitti dataset, if I want to convert my dataset into xviz protocol, maybe json files, are there anything guides?
Thanks.
Best wishes.

**Comment by jon-tri** [comment]
Have you already looked at this: https://github.com/uber/xviz-data ?

**Comment by LinLidi** [comment]
@jon-tri I had got it. thanks so much.
