### ISSUE TITLE
Why can the client receive only one .glb file when live mode is turned on?

### ISSUE THREAD

**Issue by zyqqqq** [uber/xviz#490]
When both server and client are turned on in live mode, the client can only receive one .glb file(metadata), But the remaining .glb file(state_update)  cannot be receive . How can I receive all. GLB files?  And Why still need a JSON file to record timestamps when Live mode is turned on？

Here are the commands I used to turn on live mode
![server](https://user-images.githubusercontent.com/37929979/60694665-73593f80-9f11-11e9-93e5-50a38ef18805.png)
![client](https://user-images.githubusercontent.com/37929979/60694670-78b68a00-9f11-11e9-9a0c-2f9f002f2750.png)

**Comment by twojtasz** [comment]
That should not be the case. Let me try to reproduce

**Comment by roarcurry** [comment]
It seems that the instance of XVIZLiveLoader in `streetscape.gl/examples/get-started/src/log-from-live.js`  lacks of one property "session_type: 'live'".
Because in line 120 of `xviz/modules/server/src/server/xviz-provider-session.js`,  `params.session_type` is `undefined`.

**Comment by zyqqqq** [comment]
I did it!!!!  thank you very much
