### ISSUE TITLE
color map for lidar points?

### ISSUE THREAD

**Issue by EgalYue** [uber/xviz#505]
Hi all,
Dose anyone knows how to get a **colorful lidar points map**, like following:

 
![color](https://user-images.githubusercontent.com/19492574/61933457-81eac200-afb8-11e9-901a-67171e8a6c62.png)

I know the code is here:
https://github.com/uber/xviz/blob/e11f245a9cab6d5627a2c0113effb967bdb7e294/examples/converters/kitti/src/parsers/parse-lidar-points.js#L47

but i dont know **the function between RGB  3 channels and the height(z axis) of lidar points**? 

Thanks !

**Comment by twojtasz** [comment]
This is actually a builtin style for point data.
See in the example https://github.com/uber/streetscape.gl/blob/master/examples/get-started/src/constants.js#L53

And the docs at
https://github.com/uber/xviz/blob/master/docs/protocol-schema/style-specification.md#point
