### ISSUE TITLE
Point Cloud Compression

### ISSUE THREAD

**Issue by ibgreen** [uber/xviz#51]
glTF version 2 with the GLB container supports the draco compression extension.

The XVIZWriter has an option for this but it is currently disabled as it was not working as expected. We need to work with `@loaders.gl/gltf` to fix this path and enable the option.

We know that draco decompression can take ~500ms to decode, but the size savings are still significant and is a valid option to add to XVIZ handling.

**Comment by twojtasz** [comment]
gltf will be dropped as we wrap up the current 0.x version and move to 1.0, where the focus will be on json & protobuf.

gltf was an attempt to balance JSON readability with binary data, but protobuf has been better from a performance perspective
