### ISSUE TITLE
How could we layout video panel at the upper right corner as illustrated by the picture below?

### ISSUE THREAD

**Issue by KevinYuk** [uber/xviz#513]
![image](https://user-images.githubusercontent.com/20220399/63081904-651e2a80-bf77-11e9-9c1d-624a10c4e69a.png)

**Comment by twojtasz** [comment]
@KevinYuk The starting point is this file
https://github.com/uber/streetscape.gl/blob/master/examples/website-demo/src/camera-panel.js

Follow the code how it is used in the website-demo.
