### ISSUE TITLE
Problem when serving generated KITTI dataset

### ISSUE THREAD

**Issue by eastlife** [uber/xviz#537]
Hello, I love this excellent project very much. When serving xviz of generated data, I cannot see the visualization in streetscape.gl. Actually I suppose the connection between xviz and streetscape.gl is established, because I can see the log "xvizserver-log: [> Connection] made" in xviz terminal, but there is no data from streetscape.gl (no lidar, black image, no velocity, etc). My dataset is generated from example KITTI dataset (a bunch of glb files). I am following this link:
https://github.com/uber/xviz/blob/master/docs/getting-started/running-the-example.md

**Comment by twojtasz** [comment]
Not sure what could be wrong.  Does the browser console list any errors?  I will try from scratch as soon as I can and see if I can reproduce.
What platform are you running on?

**Comment by eastlife** [comment]
There are many errors in the console. See the attached screenshot. And I am running on Ubuntu18.04
![Screenshot from 2019-10-28 13-49-56](https://user-images.githubusercontent.com/21313148/67703566-066b2900-f98a-11e9-97f1-fe34568b5a17.png)
![Screenshot from 2019-10-28 13-52-01](https://user-images.githubusercontent.com/21313148/67703636-269ae800-f98a-11e9-8e0e-94ee7aab1421.png)

**Comment by speculees** [comment]
This seems like it is linked to #540

**Comment by twojtasz** [comment]
@eastlife Fixed in https://github.com/uber/xviz/pull/560
