### ISSUE TITLE
Using multiple point clouds gives warning

### ISSUE THREAD

**Issue by mla2** [uber/xviz#549]
I'm trying to feed two lidar streams, one left and one right. I'm getting this on every update

`Point cloud for /lidar/left overwriting previous cloud`

I'm feeding alternating left and right, with incremental update. It seems to work, but the warning is a bit concerning. Am I doing something wrong, or is this bug, or a limitation?

It's a bit hard to merge them since they have a different transform and arrive with different time stamps. So sending them as two separate streams seems very convenient.

**Comment by enricoschroeder** [comment]
Same "problem" here, I would also be interested in some insight on this topic.

**Comment by twojtasz** [comment]
@mla2 @schroederen This is a legacy warning message that is inaccurate.
I will remove it since it is no longer a valid message.
