### ISSUE TITLE
Acceleration issue with IMU custom converter

### ISSUE THREAD

**Issue by KSaikishore** [uber/xviz#567]
Acceleration values with kitti dat using ros-custom converter were close to acceleration due to gravity(g =9.8 m/s2) value unlike the values in demo.How do we get the exact acceleration and velocity values from the Imu sensor.How do we show accceleration as negative while decelerating if using the formula Math.sqrt( accel_x * accel_x + accel_y *accel_ y + accel_z * accel_z ).

**Comment by twojtasz** [comment]
the **ros-custom** example and the IMU message converter are to demonstrate how to create your own XVIZ converter for a ROS message.

So you could copy the **imu-converter.js** and customize it for your needs, converting to a value that is relevant to your use-case.
