### ISSUE TITLE
Can offer more detail doc for XVIZ data format? 

### ISSUE THREAD

**Issue by heshiwen1989** [uber/xviz#574]
Hello XVIZ Team: 

i plane to use this in realtime, so l need excellent converter to convert my data to xviz, can offer more detail for xviz format?

**Comment by jlisee** [comment]
Do the [`Protocol` pages here](https://avs.auto/#/xviz/protocol/protocol-implementations/protobuf-protocol) help?

**Comment by heshiwen1989** [comment]
Hello, You offer link: https://avs.auto/#/xviz/protocol/protocol-implementations/protobuf-protocol display is not normal, in other word, this web page do not display any content.

**Comment by jlisee** [comment]
That should should be auto-populated from [`docs/protocol-formats/protobuf-protocol.md`](https://github.com/uber/xviz/blob/01fc3b2f2e98e86c904c7b57ee8d0a7be850e770/docs/protocol-formats/protobuf-protocol.md) on GitHub.  I would check the developer console to see what issues you are having with it.

**Comment by heshiwen1989** [comment]
Hello, Another Issue: 
 Why your Offer .glb format files of kitti can not correctly parse by tinygltf lib(in c++), and more, why in gltf file, binary data size always greater than buffers' bytelength about 8-11bytes 

e.g.  gltf file parse information: 
magic: "glTF" 
version: 2
length: 2327828
model_length: 95142, in fact this is json data length 
model_format: 0,  but in tiny_gltf, this must be 0x4E4F534A = JSON format.
json data:  "{\"buffers\":[{\"byteLength\":**2232656**}],\"bufferViews\":[{\"buffer\"
binary data: xxxxxx, in total 2232666 bytes

**so that, binary data size > buffers's bytelength**

**Comment by jlisee** [comment]
Glad you found the docs, can you open that with a new issue?
