### ISSUE TITLE
Support For Other open datasets

### ISSUE THREAD

**Issue by KSaikishore** [uber/xviz#579]
Is there any work going on to add support for working of other publicly available large data sets in uber 
 AVS.

**Comment by twojtasz** [comment]
@KSaikishore If you had some examples we would happily link to them.  The primary motivation is to provide examples to demonstrate how to work with data. Unless the new data set is very unique it would not necessarily need to be hosted within the project.

Having said that, I am eager to get OpenDRIVE / OpenScenario support but no timeline on that.
