### ISSUE TITLE
Question: understand data matching/synchronization logic

### ISSUE THREAD

**Issue by weidezhang** [uber/xviz#582]
Hi I have a basic question. It seems the format doesn't define timestamp for lidar or obstacles. The timestamp only exists for vehicle_pose. 

How the system understand how to visualize which lidar point cloud or obstales matched with which vehicle_pose ?  Put int another word,  when comes to visualizer(streetgl), how does it aggregates/synchronizes the streaming data and shows them simultaneously ?

**Comment by mahaogithub** [comment]
Hello,
I'm also studying avs now. Do you know how to visualize data in real time?

**Comment by weidezhang** [comment]
close this. since it's answered in slack channel.
