### ISSUE TITLE
Issue with XvizFakePose orientation

### ISSUE THREAD

**Issue by KSaikishore** [uber/xviz#587]
I have a nuscene data converted to nuscene bag fomat which has lidar point cloud as one of the ros topic. 
When i visualized the nuscend bag on streetscape.gl by mapping XvizFakePose converter to point cloud ros topic(tried mapping with other topics as well)my vehicle orientation is not alligned properly with the road.How do i rectify that.

**Comment by twojtasz** [comment]
@KSaikishore The **XvizFakePose** generates a **pose** stream required by the visualizer.  It simply outputs a fixed position and no orientation.

You would have to create your own converter to output a position & orientation, then register it and setup the configuration for it in order for it to work.  The **ros-custom** example should demonstrate this for you.
