### ISSUE TITLE
Python: Working with classes and style_class

### ISSUE THREAD

**Issue by sylvaintouret** [uber/xviz#593]
Hello,

I'm having issue with the python implementation to define style_classes and classes for streams. 

1. Defining classes on a stream, for example in the circle scenario:
```python 
    builder.primitive('/circle').circle([0.0, 0.0, 0.0], self._radius).classes('Bike')
```
To fix this i had to change the function _format_primitive in  primitive.py:
from : 
```python 
    base.classes = self._classes
```
to : 
```python 
    [base.classes.append(cls) for cls in  self._classes]
```
Now this seems to work to apply the classe in the output at least. Now comes the styling for that class. My understanding is that i should be able to do this by building the metadata like this : 

```python
    builder.stream("/circle")\
    .coordinate(xviz.COORDINATE_TYPES.IDENTITY)\
     .stream_style({'fill_color': [200, 0, 70, 128]})\
    .category(xviz.CATEGORY.PRIMITIVE)\
    .type(xviz.PRIMITIVE_TYPES.CIRCLE)\
    .style_class("Car", {'fill_color': [200, 200, 70, 128]})\
    .style_class("Bike", {'fill_color': [0, 200, 70, 128]})
```

I was kinda of able to at least not make it crash by:

1. Adding the build_class_style function in base_builder.py

```python

    def build_class_style(name, style):
        '''
        Create StyleObjectValue from dictionary. It basically deal with list of bytes.
        '''
        return StyleClass(name=name, style=build_object_style(style))
```

2. Replacing the function style_class in metadata.py by this : 

```python
    from xviz_avs.builder.base_builder import build_class_style
    (...)
    def style_class(self, name, style):
        if not self._stream_id:
            self._logger.error('A stream must set before adding a style rule.')
            return self

        self._temp_stream.style_classes.append(build_class_style(name, style))
        return self
```

3. Results:

Well, this is where it gets rough for me because my understanding of protobuf still sucks. The result i get is that the class i define for my circle is now visible in the circle tool tip like it should be, but the  circle is now fully white. 

![image](https://user-images.githubusercontent.com/35398067/82301754-fca62300-99b8-11ea-968a-08a25f757252.png)

I hope everything is clear. Any help is welcome on this.

**Comment by sylvaintouret** [comment]
It seems to be coming from the color definition itself, because other values seem to be working (like stroke_width)

**Comment by sylvaintouret** [comment]
Fixed it by adding this in function _format_primitive in primitive.py. (May hurt sensitive eyes.)

Basically i am manually merging the style from the class to the style from the object. Could not find a better solution for now

```python
    for cls in  self._classes:
        # merge style if class found in streams?
        base.classes.append(cls)
        classes = self._metadata.streams._values[self._stream_id].style_classes._values
        for c in classes:
          if c.name == cls:
                base.style.MergeFrom(c.style)
```

**Comment by jlisee** [comment]
@twojtasz

**Comment by twojtasz** [comment]
Having worked on the Declarative UI recently, the issues you are running into are due to the use of Protobuf Types directly, and a lack of test coverage.

I'm working through the test coverage issue to expose these cases.

**Comment by sylvaintouret** [comment]
Could you include the fix for classes which seems to be working for me 
function _format_primitive in primitive.py:
`[base.classes.append(cls) for cls in  self._classes]`

I've been using it for a while and it does fix at least the class definition even though i have to use stream styling instead of class styling

**Comment by sylvaintouret** [comment]
Thanks for the update :)

**Comment by twojtasz** [comment]
I'll review this today.

**Comment by kgreenek** [comment]
Thank you for the quick review cycle!

Would you guys mind doing a minor release to pypi with this bug fix? that way I can just bump the version number instead of having to package a wheel myself to get this in. I'm using it now

**Comment by twojtasz** [comment]
I'll try to get a release out today, but not until this evening.

**Comment by twojtasz** [comment]
Hitting a test failure i'm fixing first then will release
