### ISSUE TITLE
laser scanner relative to GPS position, what does this position mean?

### ISSUE THREAD

**Issue by bigablecat** [uber/xviz#659]
Since this is an identical position for all points, what does this position mean?

In kitti example, 
https://github.com/uber/xviz/blob/master/examples/converters/kitti/src/converters/lidar-converter.js
it is a fix set of values { x: 0.81, y: -0.32, z: 1.73}

In nutonomy example, it is extracted from the first frame
https://github.com/uber/xviz/blob/master/examples/converters/nutonomy/src/converters/lidar-converter.js

x = sensorCalibrations.LIDAR_TOP.translation[0];
y = sensorCalibrations.LIDAR_TOP.translation[1];
z = sensorCalibrations.LIDAR_TOP.translation[2];

when importing an new set of data, where should I get this position? 
The first point of GPS? Is that right?

**Comment by twojtasz** [comment]
@bigablecat the first value `{ x: 0.81, ...}` is the pose at the metadata level.  This acts as a transform from VEHICLE_RELATIVE to the lidar origin.  It is useful if you are interpreting lidar data that is raw and not pre-transformed to some other reference frame.

As for where you need to get that, it it depends on your data or platform.  I'm not sure about the details of the nutonomy format and why the first value is being used.  It does seem a bit odd.

Normally, you would simply know the layout of the sensors on your platform and input as such.
