### ISSUE TITLE
Occupancy grid visualisatioin

### ISSUE THREAD

**Issue by shreyas2311** [uber/xviz#660]
Is there any way to visualize occupancy grids on xviz efficiently (for example as an underlying image)? Right now I have to iterate through each cell and plot them as points which is taking too much time to process. I would be delighted to have any suggestions. Thanks.

**Comment by twojtasz** [comment]
We don't have anything out of the box.  Having some uniformed space subdivision that can be represented would be nice (ie something like a voxel type almost).

I'll keep this in mind, but for the time being we don't have one.

**Comment by shreyas2311** [comment]
Alright thanks.
