### ISSUE TITLE
what deos "WARNING: XVIZ Protobuf files are unstable, do not use" mean?

### ISSUE THREAD

**Issue by JianXinyu** [uber/xviz#671]
First, awesome project! I'm trying to use it in our project. 

At the beginning of every `.proto` file, there is such a warning. Why it's unstable? I refer to the [doc](https://avs.auto/#/xviz/protocol/protocol-implementations/protobuf-protocol), and it says "the Prototuf schema for XVIZ is under active development.". So, can I use it or not? If not, how to incorporate XVIZ in my C++ project? 

Thanks!

**Comment by twojtasz** [comment]
@JianXinyu yes, documentation doesn't update at the same speed as development practices :p. The protobuf's are completely fine to use and preferred in nearly all cases.  our glTF will be deprecated at some point as protobuf is across the board easier to integrate with.
